### ISSUE TITLE
"the hostname is not yet whitelisted in MoneyMoney"

### ISSUE THREAD

**Issue by dvcrn** [teal-bauer/moneymoney-ext-trading212#1]
Hi,

thanks for creating this! I tried installing it on the latest beta but getting

> Cannot create connection to server https://live.trading212.com/api/v0/equity/account/info because the hostname is not yet whitelisted in MoneyMoney.
> Please contact our support with this error message, and we will fix this issue as soon as possible

Version: 

> 0:49:40  Started MoneyMoney [Beta] version 2.4.36 (449) on macOS 14.3.1 (ARM).

Am I on the wrong version?

**Comment by teal-bauer** [comment]
The latest MoneyMoney version should come with a signed version of the extension, otherwise if you install it from the repo you would have to disable signature checks (which you shouldn't other than for development). I've added the signed version of version 0.31 as tag [v0.31](https://github.com/teal-bauer/moneymoney-ext-trading212/releases/tag/v0.31) - that one should work with retail versions of MoneyMoney, give it a try :)

**Comment by dvcrn** [comment]
Hmm not having success with this. Did you mean to attach something (like the signed package) to the tag? 

/E: okay I just disabled signature check for the time being. Works now!

**Comment by teal-bauer** [comment]
No, it's just tagged, the lua file in the tagged commit has a trailing signature in the text, that should allow it to be used with retail MoneyMoney. I understand from the manufacturer of MoneyMoney that it should include the extension in the latest version as well, but I'm traveling and cannot check myself at this time.
